### ISSUE TITLE
Connection reset by peer error

### ISSUE THREAD

**Issue by 3301n** [scrazzz/maskurl#1]
Getting the error:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/github/maskurl/maskurl.py", line 77, in <module>
    prompt()
  File "/home/kali/github/maskurl/maskurl.py", line 61, in prompt
    r = requests.get(f'https://is.gd/create.php?format=json&url={uparse.quote(main_url)}')
  File "/home/kali/.local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by scrazzz** [comment]
1. Can you send the full traceback? I noticed that the first line says there is an error above this error.
2. There is no exact reason for "104 Connection reset by peer" error. [It can be due to many things](https://stackoverflow.com/a/251265).
3. Try using a VPN and see if that works.

**Comment by scrazzz** [comment]
Closing this issue now
